// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ba0d6233-a268-47ba-9b2d-39f639157ba2",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "7fa8ecbaf156431b81eeaf03fac7d336",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
